# Generated by Django 5.2.7 on 2025-11-04 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='short',
            field=models.CharField(default='baf448', max_length=8, unique=True),
        ),
    ]
