# Generated by Django 5.2.7 on 2025-11-04 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_alter_url_short'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='short',
            field=models.CharField(default='367199', max_length=8, unique=True),
        ),
    ]
