# Generated by Django 5.2.7 on 2025-11-04 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_alter_url_short'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='url',
            name='short',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='url',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
