# Generated by Django 5.2.7 on 2025-11-04 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0004_remove_url_created_at_alter_url_short_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='short',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
