# Generated by Django 5.2.7 on 2025-11-04 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0005_alter_url_short'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
