# Generated by Django 5.2.7 on 2025-11-05 08:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0007_url_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='url',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
