# Generated by Django 5.2.7 on 2025-10-27 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greeting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
